require 'dacpclient/tag'
require 'dacpclient/tagcontainer'

module DACPClient
  module DMAPParser
    # The TagDefinition class describes the tags
    TagDefinition = Struct.new(:tag, :type, :name) do
      def self.find key
        Types.find { |a| a.tag.to_s == key.to_s }
      end
      
      def inspect
        "#{tag} (#{name}: #{type})"
      end

      def to_s
        "#{tag} (#{name}: #{type})"
      end
    end

    # Sources:
    # https://github.com/chendo/dmap-ng/blob/master/lib/dmap/tag_definitions.rb
    # https://code.google.com/p/ytrack/wiki/DMAP
    # https://code.google.com/p/tunesremote-se/wiki/ContentCodes
    # https://raw.github.com/mattstevens/dmap-parser/master/dmap_parser.c
    # /content-codes
    Types = [
      TagDefinition.new('mcon', :container, 'dmap.container'),
      TagDefinition.new('msrv', :container, 'dmap.serverinforesponse'),
      TagDefinition.new('msml', :container, 'dmap.msml'),
      TagDefinition.new('mccr', :container, 'dmap.contentcodesresponse'),
      TagDefinition.new('mdcl', :container, 'dmap.dictionary'),
      TagDefinition.new('mlog', :container, 'dmap.loginresponse'),
      TagDefinition.new('mupd', :container, 'dmap.updateresponse'),
      TagDefinition.new('avdb', :container, 'daap.serverdatabases'),
      TagDefinition.new('mlcl', :container, 'dmap.listing'),
      TagDefinition.new('mlit', :container, 'dmap.listingitem'),
      TagDefinition.new('mbcl', :container, 'dmap.bag'),
      TagDefinition.new('adbs', :container, 'daap.returndatabasesongs'),
      TagDefinition.new('aply', :container, 'daap.databaseplaylists'),
      TagDefinition.new('apso', :container, 'daap.playlistsongs'),
      TagDefinition.new('mudl', :container, 'dmap.deletedidlisting'),
      TagDefinition.new('abro', :container, 'daap.databasebrowse'),
      TagDefinition.new('abal', :container, 'daap.browsealbumlisting'),
      TagDefinition.new('abar', :container, 'daap.browseartistlisting'),
      TagDefinition.new('abcp', :container, 'daap.browsecomposerlisting'),
      TagDefinition.new('abgn', :container, 'daap.browsegenrelisting'),
      TagDefinition.new('prsv', :container, 'daap.resolve'),
      TagDefinition.new('arif', :container, 'daap.resolveinfo'),
      TagDefinition.new('casp', :container, 'dacp.speakers'),
      TagDefinition.new('caci', :container, 'dacp.controlint'),
      TagDefinition.new('cmpa', :container, 'dacp.pairinganswer'),
      TagDefinition.new('cacr', :container, 'dacp.cacr'),
      TagDefinition.new('cmcp', :container, 'dmcp.controlprompt'),
      TagDefinition.new('cmgt', :container, 'dmcp.getpropertyresponse'),
      TagDefinition.new('cmst', :container, 'dmcp.status'),
      TagDefinition.new('agal', :container, 'daap.albumgrouping'),
      TagDefinition.new('minm', :string, 'dmap.itemname'),
      TagDefinition.new('msts', :string, 'dmap.statusstring'),
      TagDefinition.new('mcna', :string, 'dmap.contentcodesname'),
      TagDefinition.new('asal', :string, 'daap.songalbum'),
      TagDefinition.new('asaa', :string, 'daap.songalbumartist'),
      TagDefinition.new('asar', :string, 'daap.songartist'),
      TagDefinition.new('ascm', :string, 'daap.songcomment'),
      TagDefinition.new('asfm', :string, 'daap.songformat'),
      TagDefinition.new('aseq', :string, 'daap.songeqpreset'),
      TagDefinition.new('asgn', :string, 'daap.songgenre'),
      TagDefinition.new('asdt', :string, 'daap.songdescription'),
      TagDefinition.new('asul', :string, 'daap.songdataurl'),
      TagDefinition.new('ceWM', :string, 'com.apple.itunes.welcome-message'),
      TagDefinition.new('ascp', :string, 'daap.songcomposer'),
      TagDefinition.new('assu', :string, 'daap.sortartist'),
      TagDefinition.new('assa', :string, 'daap.sortalbum'),
      TagDefinition.new('agrp', :string, 'daap.songgrouping'),
      TagDefinition.new('cann', :string, 'daap.nowplayingtrack'),
      TagDefinition.new('cana', :string, 'daap.nowplayingartist'),
      TagDefinition.new('canl', :string, 'daap.nowplayingalbum'),
      TagDefinition.new('cang', :string, 'daap.nowplayinggenre'),
      TagDefinition.new('cmnm', :string, 'dacp.devicename'),
      TagDefinition.new('cmty', :string, 'dacp.devicetype'),
      TagDefinition.new('cmpg', :hex, 'dacp.pairingguid'), # hex string
      TagDefinition.new('mper', :uint64, 'dmap.persistentid'),
      TagDefinition.new('canp', :uint64, 'dacp.nowplaying'),
      TagDefinition.new('cmpy', :uint64, 'dacp.passguid'),
      TagDefinition.new('mstt', :uint32, 'dmap.status'), # http status??
      TagDefinition.new('mcnm', :uint32, 'dmap.contentcodesnumber'),
      TagDefinition.new('miid', :uint32, 'dmap.itemid'),
      TagDefinition.new('mcti', :uint32, 'dmap.containeritemid'),
      TagDefinition.new('mpco', :uint32, 'dmap.parentcontainerid'),
      TagDefinition.new('mimc', :uint32, 'dmap.itemcount'),
      TagDefinition.new('mrco', :uint32, 'dmap.returnedcount'),
      TagDefinition.new('mtco', :uint32, 'dmap.containercount'),
      TagDefinition.new('mstm', :uint32, 'dmap.timeoutinterval'),
      TagDefinition.new('msdc', :uint32, 'dmap.databasescount'),
      TagDefinition.new('msma', :uint32, 'dmap.speakermachineaddress'),
      TagDefinition.new('mlid', :uint32, 'dmap.sessionid'),
      TagDefinition.new('assr', :uint32, 'daap.songsamplerate'),
      TagDefinition.new('assz', :uint32, 'daap.songsize'),
      TagDefinition.new('asst', :uint32, 'daap.songstarttime'),
      TagDefinition.new('assp', :uint32, 'daap.songstoptime'),
      TagDefinition.new('astm', :uint32, 'daap.songtime'),
      TagDefinition.new('msto', :uint32, 'dmap.utcoffset'),
      TagDefinition.new('cmsr', :uint32, 'dmcp.mediarevision'),
      TagDefinition.new('caas', :uint32, 'dacp.albumshuffle'),
      TagDefinition.new('caar', :uint32, 'dacp.albumrepeat'),
      TagDefinition.new('cant', :uint32, 'dacp.remainingtime'),
      TagDefinition.new('cmmk', :uint32, 'dmcp.mediakind'),
      TagDefinition.new('cast', :uint32, 'dacp.tracklength'),
      TagDefinition.new('asai', :uint32, 'daap.songalbumid'),
      TagDefinition.new('aeNV', :uint32, 'com.apple.itunes.norm-volume'),
      TagDefinition.new('cmvo', :uint32, 'dmcp.volume'),
      TagDefinition.new('mcty', :uint16, 'dmap.contentcodestype'),
      TagDefinition.new('asbt', :uint16, 'daap.songsbeatsperminute'),
      TagDefinition.new('asbr', :uint16, 'daap.songbitrate'),
      TagDefinition.new('asdc', :uint16, 'daap.songdisccount'),
      TagDefinition.new('asdn', :uint16, 'daap.songdiscnumber'),
      TagDefinition.new('astc', :uint16, 'daap.songtrackcount'),
      TagDefinition.new('astn', :uint16, 'daap.songtracknumber'),
      TagDefinition.new('asyr', :uint16, 'daap.songyear'),
      TagDefinition.new('ated', :uint16, 'daap.supportsextradata'),
      TagDefinition.new('asgr', :uint16, 'daap.supportsgroups'),
      TagDefinition.new('mikd', :byte, 'dmap.itemkind'),
      TagDefinition.new('casu', :byte, 'dacp.su'),
      TagDefinition.new('msau', :byte, 'dmap.authenticationmethod'),
      TagDefinition.new('mstu', :byte, 'dmap.updatetype'),
      TagDefinition.new('asrv', :byte, 'daap.songrelativevolume'),
      TagDefinition.new('asur', :byte, 'daap.songuserrating'),
      TagDefinition.new('asdk', :byte, 'daap.songdatakind'),
      TagDefinition.new('caps', :byte, 'dacp.playstatus'),
      TagDefinition.new('cash', :byte, 'dacp.shufflestate'),
      TagDefinition.new('carp', :byte, 'dacp.repeatstate'),
      TagDefinition.new('muty', :byte, 'dmap.updatetype'),
      TagDefinition.new("f\215ch", :byte, 'dmap.haschildcontainers'),
      TagDefinition.new('msas', :byte, 'dmap.authenticationschemes'),
      TagDefinition.new('cavs', :bool, 'dacp.visualizer'),
      TagDefinition.new('cafs', :bool, 'dacp.fullscreen'),
      TagDefinition.new('ceGS', :bool, 'com.apple.itunes.genius-selectable'),
      TagDefinition.new('mslr', :bool, 'dmap.loginrequired'),
      TagDefinition.new('msal', :bool, 'dmap.supportsautologout'),
      TagDefinition.new('msup', :bool, 'dmap.supportsupdate'),
      TagDefinition.new('mspi', :bool, 'dmap.supportspersistenids'),
      TagDefinition.new('msex', :bool, 'dmap.supportsextensions'),
      TagDefinition.new('msbr', :bool, 'dmap.supportsbrowse'),
      TagDefinition.new('msqy', :bool, 'dmap.supportsquery'),
      TagDefinition.new('msix', :bool, 'dmap.supportsindex'),
      TagDefinition.new('msrs', :bool, 'dmap.supportsresolve'),
      TagDefinition.new('asco', :bool, 'daap.songcompliation'),
      TagDefinition.new('asdb', :bool, 'daap.songdisabled'),
      TagDefinition.new('abpl', :bool, 'daap.baseplaylist'),
      TagDefinition.new('aeSP', :bool, 'com.apple.itunes.smart-playlist'),
      TagDefinition.new('aePP', :bool, 'com.apple.itunes.is-podcast-playlist'),
      TagDefinition.new('aePS', :bool, 'com.apple.itunes.special-playlist'),
      TagDefinition.new('aeSG', :bool, 'com.apple.itunes.saved-genius'),
      TagDefinition.new('aeFP', :bool, 'com.apple.itunes.req-fplay'),
      TagDefinition.new('aeHV', :bool, 'com.apple.itunes.has-video'),
      TagDefinition.new('caia', :bool, 'dacp.isavailiable'),
      TagDefinition.new('ceVO', :bool, 'com.apple.itunes.voting-enabled'),
      TagDefinition.new('aeSV', :version,
                        'com.apple.itunes.music-sharing-version'),
      TagDefinition.new('mpro', :version, 'dmap.protocolversion'),
      TagDefinition.new('apro', :version, 'daap.protocolversion'),
      TagDefinition.new('musr', :version, 'dmap.serverrevision'),
      TagDefinition.new('mstc', :date, 'dmap.utc-time'),
      TagDefinition.new('asda', :date, 'daap.songdateadded'),
      TagDefinition.new('asdm', :date, 'daap.songdatemodified'),
      TagDefinition.new('ceJC', :bool, 'com.apple.itunes.jukebox-client-vote'),
      TagDefinition.new('ceJI', :bool, 'com.apple.itunes.jukebox-current'),
      TagDefinition.new('ceJS', :uint16, 'com.apple.itunes.jukebox-score'),
      TagDefinition.new('ceJV', :bool, 'com.apple.itunes.jukebox-vote'),
      TagDefinition.new('ceQR', :container,
                        'com.apple.itunes.playqueue-contents-response'),
      TagDefinition.new('ceQS', :container,
                        'com.apple.itunes.playqueue-contents-???'),
      TagDefinition.new('ceQs', :uint64, 'com.apple.itunes.playqueue-id'),
      TagDefinition.new('ceQa', :string, 'com.apple.itunes.playqueue-album'),
      TagDefinition.new('ceQg', :string, 'com.apple.itunes.playqueue-genre'),
      TagDefinition.new('ceQn', :string, 'com.apple.itunes.playqueue-name'),
      TagDefinition.new('ceQr', :string, 'com.apple.itunes.playqueue-artist'),
      TagDefinition.new('msml', :container, 'msml'),
      TagDefinition.new('aeGs', :bool, 'com.apple.itunes.can-be-genius-seed'),
      TagDefinition.new('aprm', :short, 'daap.playlistrepeatmode'),
      TagDefinition.new('apsm', :short, 'daap.playlistshufflemode'),
      TagDefinition.new('cmpr', :version, 'dmcp.protocolversion'),
      TagDefinition.new('capr', :version, 'dacp.protocolversion'),
      TagDefinition.new('ppro', :version, 'unknown.version')
    ].freeze
  end
end